name: Build and Push Docker Image

on:
  push:
    branches:
      - main   # Укажите нужную ветку, например, main или master
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Проверка репозитория
      - name: Checkout code
        uses: actions/checkout@v3

      # Логин в Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Сборка и публикация Docker-образов для нескольких платформ
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/amd64,linux/arm64

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/kino-cat-bot-go:latest
          platforms: linux/amd64,linux/arm64
